version: "3"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile-app
    image: app
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm start]
